
#ifndef TVG_CONFIG_H
#define TVG_CONFIG_H

#define THORVG_SW_RASTER_SUPPORT 1
//#define THORVG_GL_RASTER_SUPPORT 1
#define THORVG_SVG_LOADER_SUPPORT 1
//#define THORVG_AVX_VECTOR_SUPPORT 1
#define THORVG_CAPI_BINDING_SUPPORT 1
//#define THORVG_LOG_ENABLED true

#endif //TVG_CONFIG_H
