
#ifndef TVG_CONFIG_H
#define TVG_CONFIG_H

#define THORVG_SW_RASTER_SUPPORT true
//#define THORVG_GL_RASTER_SUPPORT true
#define THORVG_SVG_LOADER_SUPPORT true
//#define THORVG_AVX_VECTOR_SUPPORT true
#define THORVG_CAPI_BINDING_SUPPORT true
//#define THORVG_LOG_ENABLED true

#endif //TVG_CONFIG_H
